### ISSUE TITLE
Captioning challenge submission on codalab raising error

### ISSUE THREAD

**Issue by MRishiK99** [cocodataset/cocodataset.github.io#55]
I tried evaluating my model on caption test2014 set using the codalab server. I tried submitting the result file as mentioned in the coco tasks page : https://cocodataset.org/#upload. 
But I get this error:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmpDLvvrP/run/program/cocoEvalCapCoda.py", line 65, in <module>
    cocoRes = coco.loadRes(resFile_val)
  File "/tmp/codalab/tmpDLvvrP/run/program/pycocotools/coco.py", line 275, in loadRes
    anns    = json.load(open(resFile))
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmpDLvvrP/run/input/res/captions_val2014__results.json'

**Comment by amazingYX** [comment]
I meet similar problem. Have ever solved it?
